/*

 MAZE_TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\Users\max\repos\gameboy_dev_tutorials\sprites\buildings\dungeon_test_8x8.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mazeWidth 32
#define mazeHeight 32
#define mazeBank 0

extern unsigned char maze[];

/* End of MAZE_TEST.H */
