/*

 DUNGEON_TILES_TEXT_8X8.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define dungeon_tilesBank 0
/* Start of tile array. */
extern unsigned char dungeon_tiles[];

/* End of DUNGEON_TILES_TEXT_8X8.H */
