//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_go_sprites_H
#define METASPRITE_go_sprites_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define go_sprites_TILE_ORIGIN 0
#define go_sprites_TILE_W 8
#define go_sprites_TILE_H 16
#define go_sprites_WIDTH 48
#define go_sprites_HEIGHT 16
#define go_sprites_TILE_COUNT 6
#define go_sprites_PALETTE_COUNT 1
#define go_sprites_COLORS_PER_PALETTE 4
#define go_sprites_TOTAL_COLORS 4
#define go_sprites_PIVOT_X 24
#define go_sprites_PIVOT_Y 8
#define go_sprites_PIVOT_W 48
#define go_sprites_PIVOT_H 16
extern const metasprite_t* const go_sprites_metasprites[1];

BANKREF_EXTERN(go_sprites)

extern const palette_color_t go_sprites_palettes[4];
extern const uint8_t go_sprites_tiles[96];

#endif
