//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_H
#define METASPRITE_test_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_TILE_ORIGIN 0
#define test_TILE_W 8
#define test_TILE_H 16
#define test_WIDTH 16
#define test_HEIGHT 16
#define test_TILE_COUNT 12
#define test_PALETTE_COUNT 1
#define test_COLORS_PER_PALETTE 4
#define test_TOTAL_COLORS 4
#define test_PIVOT_X 8
#define test_PIVOT_Y 8
#define test_PIVOT_W 16
#define test_PIVOT_H 16
extern const metasprite_t* const test_metasprites[3];

BANKREF_EXTERN(test)

extern const palette_color_t test_palettes[4];
extern const uint8_t test_tiles[192];

#endif
